.TH locksmith

.SH NAME

locksmith \- a simple password manager with a built\-in command shell.

.SH DESCRIPTION

locksmith (yes, it IS stylized in lowercase) is a (UNIX-like exclusive) simple, secure and blazingly
fast password manager written entirely in C. It comes with a builtin command-shell for maximum effectivity.

.SH SYNOPSIS

.B locksmith
[\fBoptions\fR]

.SH OPTIONS

.TP
.BR \-\-help:
Prints the locksmith help message.
